-- MySQL Script generated by MySQL Workbench
-- ter 11 ago 2026 16:37:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loja_jogo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja_jogo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja_jogo` ;
USE `loja_jogo` ;

-- -----------------------------------------------------
-- Table `loja_jogo`.`desenvolvedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_jogo`.`desenvolvedor` (
  `id_desenvolvedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_desenvolvedor`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja_jogo`.`jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_jogo`.`jogo` (
  `id_jogo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `data_lancamento` TIMESTAMP NOT NULL,
  `preco` DECIMAL(5,2) NOT NULL,
  `genero` VARCHAR(100) NOT NULL,
  `foto` TEXT NOT NULL,
  `id_desenvolvedor` INT NOT NULL,
  PRIMARY KEY (`id_jogo`),
  INDEX `fk_jogo_desenvolvedor1_idx` (`id_desenvolvedor` ASC) VISIBLE,
  CONSTRAINT `fk_jogo_desenvolvedor1`
    FOREIGN KEY (`id_desenvolvedor`)
    REFERENCES `loja_jogo`.`desenvolvedor` (`id_desenvolvedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja_jogo`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_jogo`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja_jogo`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_jogo`.`compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `forma_pagamento` VARCHAR(45) CHARACTER SET 'armscii8' NOT NULL,
  `data_compra` TIMESTAMP NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_jogo` INT NOT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_compra_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_compra_jogo1_idx` (`id_jogo` ASC) VISIBLE,
  CONSTRAINT `fk_compra_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `loja_jogo`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_jogo1`
    FOREIGN KEY (`id_jogo`)
    REFERENCES `loja_jogo`.`jogo` (`id_jogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `loja_jogo` ;

-- -----------------------------------------------------
-- Placeholder table for view `loja_jogo`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_jogo`.`view1` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `loja_jogo`.`view2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_jogo`.`view2` (`id` INT);

-- -----------------------------------------------------
-- View `loja_jogo`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja_jogo`.`view1`;
USE `loja_jogo`;


-- -----------------------------------------------------
-- View `loja_jogo`.`view2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja_jogo`.`view2`;
USE `loja_jogo`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
